name: "Cloudfix-Linter"
inputs:
  mock_recommendations:
    description: boolean to activate mock recommendations
    required: true
    default: 'true'
  tf_cli_config_credentials_token: 
    description: terraform cli config credentials token
    required: true
  GITHUB_TOKEN:
    description: 'Github token of the repository (automatically created by Github)'
    default: ${{ github.token }}
    required: true
  pr_number:
    description: 'Pull request id'
    required: true
  repository:
    description: repository_owner/repository_name
    required: true
  cloudfix_username:
    description: cloudfix username
    required: false
  cloudfix_password:
    description: cloudfix password
    required: false

on:
  pull_request:

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: trilogy-group/cloudfix-linter-github-action
        path: mainRepo

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        # terraform_version: 0.13.0:
        cli_config_credentials_token: ${{ inputs.tf_cli_config_credentials_token }}

    - name: Comment Reccomendation
      id: prcomment
      env:
        GH_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        CLOUDFIX_USERNAME: ${{ inputs.cloudfix_username }}
        CLOUDFIX_PASSWORD: ${{ inputs.cloudfix_password }}
        ENABLE_MOCK_RECOMMENDATION: "${{ inputs.mock_recommendations }}"
        pr_number: ${{ inputs.pr_number }}
        repository: ${{ inputs.repository }}
      run: echo ${{ inputs.mock_recommendations }}; sh mainRepo/script.sh
      shell: bash
