name: "Cloudfix-Linter"
inputs:
  tf_cli_config_credentials_token: 
    description: terraform cli config credentials token
    required: true
  GITHUB_TOKEN:
    description: 'Github token of the repository (automatically created by Github)'
    default: ${{ github.token }}
    required: true
  pr_number:
    description: 'Manual pull request number'
    required: true
  repository:
    description: repository_owner/repository_name
    required: true

on:
  pull_request:

permissions:
  pull-requests: write

runs:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        # terraform_version: 0.13.0:
        cli_config_credentials_token: ${{ inputs.tf_cli_config_credentials_token }}
    
    - name: Comment Reccomendation
      id: prcomment
      env:
        GH_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      run: export pr_number=${{ inputs.pr_number }}; export repository=${{ inputs.repository }}; sh script.sh
