name: "Cloudfix-Linter"

inputs:
  mock_recommendations:
    description: boolean to activate mock recommendations
    required: true
    default: 'false'
  GITHUB_TOKEN:
    description: 'Github token of the repository (automatically created by Github)'
    default: ${{ github.token }}
    required: true
  pr_number:
    description: 'Pull request id'
    required: true
  repository:
    description: repository_owner/repository_name
    required: true
  cloudfix_username:
    description: cloudfix username
    required: false
  cloudfix_password:
    description: cloudfix password
    required: false
  terraform_binary_path:
    description: path of the terraform binary
    required: false

on:
  pull_request:

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: trilogy-group/cloudfix-linter-github-action
        path: mainRepo
        # ref: branch-name

    - name: Comment Reccomendation
      id: prcomment
      env:
        GH_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        CLOUDFIX_USERNAME: ${{ inputs.cloudfix_username }}
        CLOUDFIX_PASSWORD: ${{ inputs.cloudfix_password }}
        ENABLE_MOCK_RECOMMENDATION: "${{ inputs.mock_recommendations }}"
        TERRAFORM_BINARY_PATH: ${{ inputs.terraform_binary_path }}
        pr_number: ${{ inputs.pr_number }}
        repository: ${{ inputs.repository }}
      run: echo $ENABLE_MOCK_RECOMMENDATION; sh mainRepo/script.sh
      shell: bash
